package com.boatarde.bilubot.flows;

public enum WorkflowAction {
    NONE, SEND_MESSAGE, DOWNLOAD, GET_NEXT_GALLERY_DL_RESULT, SEND_GALLERY_DL_RESULT, IDENTIFY_CATEGORY_STEP,
    GET_NEXT_GALLERY_DL_METADATA, TWITTER_CATEGORY, REDDIT_CATEGORY, GENERIC_CATEGORY, SEND_MEDIA_GROUP,
    UPLOAD_AND_ADD_INPUT_MEDIA, BUILD_PONG_MESSAGE
}
