package com.boatarde.bilubot.flows;

public enum WorkflowDataKey {
    BILUBOT,
    TELEGRAM_UPDATE,
    SEND_MESSAGE,
    GALLERY_DL_CURRENT_RESULT, GALLERY_DL_CURRENT_METADATA, SEND_MEDIA_GROUP, GALLERY_DL_RESULTS_ITERATOR,
    GALLERY_DL_CURRENT_RESULT_METADATA_ITERATOR, GALLERY_DL_RESULTS
}
